#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/Rahat87942R/local_manifest
BRANCH=main 

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -u https://github.com/Havoc-OS/android_manifest.git -b eleven
git config --global user.email linuxxxkali33@gmail.com
git config --global user.name RON1N9

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

pwd
ls

cd /tmp/rom
